### ISSUE TITLE
Right pane scrolling up on change

### ISSUE THREAD

**Issue by meain** [rabite0/hunter#19]
Not sure what is causing the issue or if it is supposed to be there, I am on commit `4c1f7e8` of master.

![gif](https://i.imgur.com/RsRpfO4.gif)

**Comment by rabite0** [comment]
That's intended behaviour :). 

It's supposed to be a slide up animation.

I did this first as a joke when I saw how fast rendering is with Rust, but I actually started really liking it. Makes scrolling feel nice and smooth, instead of abruptly switching between previews. But I'm aware that other people might think differently.

If you don't like it, you can easily disable it. Put "animation=off" into ~/.config/hunter/config and it will disable all animations.

**Comment by meain** [comment]
Oops, sorry for not reading the docs. Thank you for the fast reply. 

Btw, great work on this.

**Comment by meain** [comment]
It was `cargo run`. I just pulled in the latest version and was trying it out.

**Comment by rabite0** [comment]
Yeah, that builds a debug version, which has a lot of overhead. On my system it easily goes up to >100% cpu usage while scrolling, but the "--release" build only uses 20-40%, depending on the content of the directory.

If you see any other issues, feel free to open a bug report.

**Comment by meain** [comment]
Yeah, it feels smooth on a release build. But I think I will stick with no animation. 

I think I am just used to it being that way.

**Comment by coldfix** [comment]
To me this behaviour feels like a bug. I would never have guessed it is intended, and it almost made me directly turn away from this program. In fact, I'd guess there are many users like me, and I'd recommend to disable it by default, since I believe it is rather irritating and unexpected for new users. Obviously, I can't speak for everyone, so just my two cents ;)
