### ISSUE TITLE
How to select a file or change a directory using fuzzy finders?

### ISSUE THREAD

**Issue by alexherbo2** [rabite0/hunter#22]
What is the equivalent to the following [lf] commands, which use [fzf] and [fd]?

**Example** – Select a file:

```
cmd select-fuzzy ${{
  lf -remote "send $id select $(fd --type file | fzf)"
}}

map s select-fuzzy
```

**Example** – Change to a directory:

```
cmd cd-fuzzy ${{
  lf -remote "send $id cd $(fd --type directory | fzf)"
}}

map g cd-fuzzy
```

[lf]: https://github.com/gokcehan/lf
[fzf]: https://github.com/junegunn/fzf
[fd]: https://github.com/sharkdp/fd

**Comment by rabite0** [comment]
This runs fzf and lf selects the file/enter dir returned by it, if I understand that correctly?

So, you're asking for integration with fzf/other tools to select files/enter directorier? That should be fairly easy to do and sounds pretty useful actually.

Right now you can filter with Ctrl(F) and search for files with S and browse through matches with Alt-S. Also you can press "/" and enter a directory with autocompletion in the minibuffer at the bottom. All available keybindings are in the README.

Btw, lf seems nice, starts up quickly and never lags. Also looks very much like ranger itself.

**Comment by alexherbo2** [comment]
Yep that’s it.

And yep it is close to [ranger], except it has no tab but a client-server architecture to communicate between instances.

[ranger]: https://ranger.github.io

**Comment by rabite0** [comment]
I'm currently working on this, but I'm wondering if separate commands for files/directories are really necessary. I was thinking about a single command that detects if the output is a file or directory and opens/selects it appropriately.

Also, right now I'm using the "enter" key to start the external process, although I might change this before I push this. It does kinda make sense though. I guess I could bind the second command to Alt(Enter), if it's desirable.

**Comment by alexherbo2** [comment]
I think select is enough and better.

**Comment by alexherbo2** [comment]
<kbd>Return</kbd> is to open files and directories – open files with the appropriate program and open directories by entering in the folder.

If you make the distinction as above, action on files will _select_, and directories _select and open_.

In addition, it will simplify the code because you opt-out the logic of files and directories.

So if I was you, I would start with a select command to see if that’s enough, and let the user with one key away to open the files and directories after the selection.

**Comment by alexherbo2** [comment]
It would be nice to have a concept of multiple selections.

**Comment by rabite0** [comment]
Well, currently Enter/Return does nothing, because it doesn't make sense to use it to open anything, since you can use either the usual movement-keys hjkl, etc. or the cursor-keys to do that. I don't think many people would use it that way.

I agree that selecting multiple files is a desirable feature. Will add that, too.

I pushed a branch called "select-prog" with the current state of things. You can define a program by adding "select_prog=<program name>" to ~/.config/hunter/config. Any issues you can find?

It probably fails if the program outputs multiple files/directories at once, I didn't consider that use-case.

**Comment by rabite0** [comment]
Ok, pushed another update for this. You can now select multiple files using an external command.

What works:
- select file/open directory
- select multiple files/directories
This also works if those files/directories are spread across multiple directories themselves. So for example, you you select /a/{b,c,d} and /e/{f,g} from fzf it will select ALL of them in turn
- move cursor to the last file that was multi-selected
There's currently no sorting of the output by the external program, so this is pretty random in the case of fzf

What doesn't work:
- parsing command options in select_prog. If you want to call "fzf -m", you need a wrapper script right now.

Open questions:
- If multiple directories are involved it might be better to not change the directory at all? In the example above( selected: /a/{b,c,d} and /e/{f,g} you'd be in e/ with the cursor on g right now. Maybe it would be better to stay in / instead? Maybe with the cursor on /e?
- Sort the output of the external command? I'd say no, as this means you don't get what you see, but it also means the cursor will be in a pretty random position that happened to be the last file in the case of fzf. It's probably better to do the sorting somewhere else (like fzf | sort or something).
- Keybinding
I dunno, Enter seems at least somewhat appropriate and it's free. Could be something else, but there aren't that many easy keys left unbound.

Anything else I'm missing? Other suggestions?

**Comment by rabite0** [comment]
Ok, pushed another update. Except for the synchronous IO issue, this seems pretty usable and stable now. I'm probably not going to bother with the asynchronous IO stuff right now. I don't think it's going to be much a problem anyway, since fzf pulls all everything into the fs-cache when it runs, so it will still be pretty fast for the most part.

**Comment by alexherbo2** [comment]
I’m not fond to opt-in select file or open directory.

**Comment by rabite0** [comment]
Oh, now I see what you mean, fzf actually behaves differently when you pipe files into it!

I was a bit confused by the commands you wrote in the beginning, since I coulnd't even see any directories in fzf when I just ran it by itself. I should have tried them as you posted them.

You're right, I will split those two functions, that makes more sense.

**Comment by rabite0** [comment]
Sooo.. this is more or less done, I merged the branch into master. 

Selecting files and entering directories are now two separate features. I also changed the keybindings. External select is now Alt(space) and external cd is Alt(/). Since space is already select and "/" does this cd-prompt-thing, this is at least consistent and logical.

By default it uses "find -type f | fzf -m" for selecting files, and "find -type d | fzf for cd to directories. You can change this, of course.

BTW, you compile hunter on your own you can also change the key bindings in the source code. You need to look into src/file_browser.rs. At the bottom is an "on_key" method. There you can change the keys if you like. Then commit with "commit -a". After that you can use git pull and it will merge the new changes into your local repo.
