### ISSUE TITLE
What is the correct spelling of the name of the project?

### ISSUE THREAD

**Issue by alexherbo2** [rabite0/hunter#23]
In the README when you refer to _hunter_, you refer to the project as _hunter_ or the program `hunter`?  Should it be spelled _hunter_ / _Hunter_?

**Comment by rabite0** [comment]
Both the project and the program are called "hunter" in lower case. I consciously chose this spelling in accordance to the old UNIX tradition.

In the same vein. the name "hunter" is kind of a joke, since it's similar to "ranger", like the development of less -> more -> most and other UNIX tools.

I won't get angry if you spell it "Hunter" tough :).

**Comment by alexherbo2** [comment]
When I see Hunter I think Hunter × Hunter lol.

**Comment by rabite0** [comment]
Haha, yes, people familiar with the manga might be reminded of HxH. :)

I was was thinking about hunter in the sense that you use it to "hunt" for the files you want to open/delete/unpack/whatever..
