### ISSUE TITLE
unsafe code should have some justification as to why it's safe

### ISSUE THREAD

**Issue by saethlin** [rabite0/hunter#62]
Specifically this code needs a good justification as to why it isn't unsound:

https://github.com/rabite0/hunter/blob/15e2f89a645f14dab7438696d50b1bef945596a3/src/fscache.rs#L67

This look to me like a "just make it compile" use of `unsafe`; I hope you can explain how I'm wrong.

**Comment by rabite0** [comment]
IIRC that was to fix compilation on FreeBSD, because fsnotify didn't implement Send/Sync for its PollWatcher at the time (even though it should have, given that it was safe due to its interface). I eventually got a simple patch merged, so it has become unnecessary now.

I guess it also masked a compiler error with that Sender, but that Sender stored in FsCache wasn't ever accessed anyway . When calling FsCache::new(), a cloned Sender is passed right to watch_fs() and then it's stored in the struct, but never touched again, since all other instances of FsCache are cloned and nothing else uses that Sender in FsCache.

Anyway, thanks for pointing that out. I have removed it.
