### ISSUE TITLE
Three dots instead of image preview using sixel

### ISSUE THREAD

**Issue by sweenu** [rabite0/hunter#83]
I am using hunter on Arch linux with wayland using the Alacritty terminal emulator.
I installed hunter with the AUR package which compiles hunter with all its features enabled however when I try the sixel graphical preview I only have three dots `...`.

I tried under X, with other terminal emulators but the result is always the same.

Any idea of what I might have missed?

**Comment by rabite0** [comment]
- Does anything change if you set graphics=unicode in `~/.config/hunter/config`? 
- Does `hunter-media` exist in your $PATH?
- Is there anything in the log (press `g`)?

**Comment by lazy-dolphin** [comment]
`alacritty` does not support sixel currently.
<https://github.com/alacritty/alacritty/issues/910>

**Comment by rabite0** [comment]
Ohhh, right, yeah... Totally missed that part.
I'm still interested in working on fixing that, but due to various circumstances I couldn't, yet. I wasn't able to work on hunter until very recently either, as you can see in the commit log.

But still, unless you put graphics=sixel explicitly in the config hunter should somewhat auto-detect the terminal's graphics support (currently only checks kitty and xterm explicitly) and otherwise default to the Unicode block drawing fallback.
